In [1]:
import numpy as np
import os
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# Bare

## N4

In [2]:

f = open("bader/bare_N4_ACF.dat",'r')
lines = f.readlines()

bader = list()
for i,line in enumerate(lines[2:-4]):
    line = line.split()  # 줄 끝의 줄 바꿈 문자를 제거한다.
    bader.append(line)
f.close()

df_bare_N4 = pd.DataFrame(bader)
df_bare_N4.drop([0],axis=1)
df_bare_N4.columns = ["#","x","y","z","charge","min_dist","atomic vol"]
df_bare_N4 = df_bare_N4.drop(['#','min_dist','atomic vol'],axis=1)

atom_list = ['C'] *20 + ['N'] * 4 + ['Ir'] * 1
df_bare_N4['atom'] = atom_list


electron = [4,5,9]
net_list = list()
for i,atom in enumerate(atom_list) :
    if atom == "C" :
        net_list.append(-float(list(df_bare_N4['charge'])[i]) + electron[0])
    if atom == "N" :
        net_list.append(-float(list(df_bare_N4['charge'])[i]) + electron[1])
    if atom == "Ir" :
        net_list.append(-float(list(df_bare_N4['charge'])[i]) + electron[2])    
        
df_bare_N4['net'] = net_list

df_bare_N4 = df_bare_N4.astype({'x':'float', 'y':'float', 'z':'float', 'charge' : 'float'})

df_bare_N4

           x         y         z    charge atom       net
0   5.400746  1.840458  5.041443  3.611563    C  0.388437
1   4.727445  0.607382  5.041366  3.978727    C  0.021273
2   5.400744  7.755845  5.041356  3.621615    C  0.378385
3   4.703790  6.513533  5.041237  3.998496    C  0.001504
4   6.961710  3.401406  5.041397  3.584946    C  0.415054
5   8.194782  4.074708  5.041264  3.967504    C  0.032496
6   1.046317  3.401356  5.041421  3.512143    C  0.487857
7   2.288617  4.098327  5.041287  3.809013    C  0.190987
8   3.304228  3.082725  5.041287  3.951383    C  0.048617
9   2.607282  1.840412  5.041442  3.515646    C  0.484354
10  5.719417  5.497914  5.041237  4.150392    C -0.150392
11  6.961726  6.194868  5.041356  3.522729    C  0.477271
12  8.194794  5.521552  5.041242  4.173810    C -0.173810
13  1.046342  6.194835  5.041380  3.507077    C  0.492923
14  2.607280  7.755809  5.041356  3.576567    C  0.423433
15  2.288646  5.497883  5.041267  4.035902    C -0.035902
16  3.304242  6.513510  5.041258  3.871898    C  0.128102
17  3.280608  0.607359  5.041366  3.985317    C  0.014683
18  5.719405  4.098367  5.041258  3.863765    C  0.136235
19  4.703784  3.082756  5.041287  4.019212    C -0.019212
20  6.777572  2.024589  5.041821  6.213004    N -1.213004
21  1.230464  2.024532  5.041819  6.257155    N -1.257155
22  6.777571  7.571709  5.041740  6.209878    N -1.209878
23  1.230463  7.571677  5.041738  6.247568    N -1.247568
24  8.194776  0.607371  5.042096  7.814689   Ir  1.185311

## N3

In [3]:

f = open("bader/bare_N3_ACF.dat",'r')
lines = f.readlines()

bader = list()
for i,line in enumerate(lines[2:-4]):
    line = line.split()  # 줄 끝의 줄 바꿈 문자를 제거한다.
    bader.append(line)
f.close()

df_bare_N3 = pd.DataFrame(bader)
df_bare_N3.drop([0],axis=1)
df_bare_N3.columns = ["#","x","y","z","charge","min_dist","atomic vol"]
df_bare_N3 = df_bare_N3.drop(['#','min_dist','atomic vol'],axis=1)

atom_list = ['C'] *21 + ['N'] * 3 + ['Ir'] * 1
df_bare_N3['atom'] = atom_list


electron = [4,5,9]
net_list = list()
for i,atom in enumerate(atom_list) :
    if atom == "C" :
        net_list.append(-float(list(df_bare_N3['charge'])[i]) + electron[0])
    if atom == "N" :
        net_list.append(-float(list(df_bare_N3['charge'])[i]) + electron[1])
    if atom == "Ir" :
        net_list.append(-float(list(df_bare_N3['charge'])[i]) + electron[2])    
        
df_bare_N3['net'] = net_list
df_bare_N3 = df_bare_N3.astype({'x':'float', 'y':'float', 'z':'float', 'charge' : 'float'})
df_bare_N3

           x         y         z    charge atom       net
0   5.394962  1.820959  5.006946  4.019057    C -0.019057
1   4.712945  0.600916  5.006491  3.934755    C  0.065245
2   5.396791  7.774360  5.007021  3.616974    C  0.383026
3   4.721059  6.531637  5.006084  4.007798    C -0.007798
4   7.003862  3.429871  5.006916  4.003714    C -0.003714
5   8.223898  4.111889  5.006450  4.060645    C -0.060645
6   1.050456  3.427973  5.007004  3.612250    C  0.387750
7   2.293181  4.103714  5.006076  3.802734    C  0.197266
8   3.310642  3.084000  5.006102  4.037279    C -0.037279
9   2.599961  1.836775  5.007095  3.622327    C  0.377673
10  5.740797  5.514183  5.006109  3.933620    C  0.066380
11  6.988008  6.224883  5.007091  3.512906    C  0.487094
12  8.227277  5.554739  5.006527  3.994921    C  0.005079
13  1.058956  6.216689  5.006905  3.489883    C  0.510117
14  2.608094  7.765848  5.006917  3.560453    C  0.439547
15  2.304909  5.511039  5.006006  4.024008    C -0.024008
16  3.313745  6.519899  5.006022  3.870023    C  0.129977
17  3.270105  0.597518  5.006555  3.950217    C  0.049783
18  5.746590  4.114161  5.006032  4.133024    C -0.133024
19  4.710664  3.078234  5.006038  4.001287    C -0.001287
20  6.833759  1.991081  5.008056  4.160746    C -0.160746
21  1.218301  2.037891  5.008101  6.076851    N -1.076851
22  6.786873  7.606559  5.008132  6.155096    N -1.155096
23  1.248011  7.576791  5.007821  6.237927    N -1.237927
24  8.203965  0.620883  5.009405  8.181503   Ir  0.818497

## N2

In [4]:

f = open("bader/bare_N2_ACF.dat",'r')
lines = f.readlines()

bader = list()
for i,line in enumerate(lines[2:-4]):
    line = line.split()  # 줄 끝의 줄 바꿈 문자를 제거한다.
    bader.append(line)
f.close()

df_bare_N2 = pd.DataFrame(bader)
df_bare_N2.drop([0],axis=1)
df_bare_N2.columns = ["#","x","y","z","charge","min_dist","atomic vol"]
df_bare_N2 = df_bare_N2.drop(['#','min_dist','atomic vol'],axis=1)

atom_list = ['C'] *22 + ['N'] * 2 + ['Ir'] * 1
df_bare_N2['atom'] = atom_list


electron = [4,5,9]
net_list = list()
for i,atom in enumerate(atom_list) :
    if atom == "C" :
        net_list.append(-float(list(df_bare_N2['charge'])[i]) + electron[0])
    if atom == "N" :
        net_list.append(-float(list(df_bare_N2['charge'])[i]) + electron[1])
    if atom == "Ir" :
        net_list.append(-float(list(df_bare_N2['charge'])[i]) + electron[2])    
        
df_bare_N2['net'] = net_list
df_bare_N2 = df_bare_N2.astype({'x':'float', 'y':'float', 'z':'float', 'charge' : 'float'})
df_bare_N2

           x         y         z    charge atom       net
0   5.433405  1.830956  4.970684  4.089140    C -0.089140
1   4.752503  0.601015  4.970652  3.982719    C  0.017281
2   5.425021  7.790555  4.970893  3.614103    C  0.385897
3   4.735388  6.542022  4.970861  4.067800    C -0.067800
4   7.029885  3.462523  4.970747  4.091955    C -0.091955
5   8.254894  4.166975  4.970745  3.970022    C  0.029978
6   1.036967  3.462489  4.970739  4.012761    C -0.012761
7   2.299033  4.128044  4.970736  3.942221    C  0.057779
8   3.334098  3.087494  4.970733  3.885091    C  0.114909
9   2.633473  1.830927  4.970680  3.919943    C  0.080057
10  5.751516  5.528233  4.970838  4.083842    C -0.083842
11  7.000537  6.251799  4.970836  3.497142    C  0.502858
12  8.254907  5.600366  4.970780  3.974609    C  0.025391
13  1.066340  6.251748  4.970745  3.548596    C  0.451404
14  2.641831  7.790535  4.970806  3.567287    C  0.432713
15  2.315366  5.528201  4.970750  4.037032    C -0.037032
16  3.331471  6.542008  4.970797  3.872890    C  0.127110
17  3.314391  0.601000  4.970630  3.988349    C  0.011651
18  5.767832  4.128076  4.970762  3.913021    C  0.086979
19  4.732764  3.087509  4.970735  4.027631    C -0.027631
20  6.880601  2.021748  4.970815  4.061152    C -0.061152
21  1.186285  2.021714  4.970829  4.162320    C -0.162320
22  6.793554  7.610646  4.970932  6.167007    N -1.167007
23  1.273315  7.610605  4.970821  6.195085    N -1.195085
24  8.254921  0.647589  4.971262  8.328283   Ir  0.671717

## N2-t

In [5]:

f = open("bader/bare_N2t_ACF.dat",'r')
lines = f.readlines()

bader = list()
for i,line in enumerate(lines[2:-4]):
    line = line.split()  # 줄 끝의 줄 바꿈 문자를 제거한다.
    bader.append(line)
f.close()

df_bare_N2t = pd.DataFrame(bader)
df_bare_N2t.drop([0],axis=1)
df_bare_N2t.columns = ["#","x","y","z","charge","min_dist","atomic vol"]
df_bare_N2t = df_bare_N2t.drop(['#','min_dist','atomic vol'],axis=1)

atom_list = ['C'] *22 + ['N'] * 2 + ['Ir'] * 1
df_bare_N2t['atom'] = atom_list


electron = [4,5,9]
net_list = list()
for i,atom in enumerate(atom_list) :
    if atom == "C" :
        net_list.append(-float(list(df_bare_N2t['charge'])[i]) + electron[0])
    if atom == "N" :
        net_list.append(-float(list(df_bare_N2t['charge'])[i]) + electron[1])
    if atom == "Ir" :
        net_list.append(-float(list(df_bare_N2t['charge'])[i]) + electron[2])    
        
df_bare_N2t['net'] = net_list
df_bare_N2t = df_bare_N2t.astype({'x':'float', 'y':'float', 'z':'float', 'charge' : 'float'})

df_bare_N2t

           x         y         z    charge atom       net
0   5.438079  1.851120  4.973223  3.596508    C  0.403492
1   4.751072  0.604763  4.972835  3.981853    C  0.018147
2   5.413590  7.812419  4.974009  4.123573    C -0.123573
3   4.721574  6.558342  4.973640  3.990593    C  0.009407
4   7.010216  3.423263  4.973706  3.506715    C  0.493285
5   8.256558  4.110297  4.974015  3.964663    C  0.035337
6   1.048908  3.447716  4.972269  4.028567    C -0.028567
7   2.302987  4.139734  4.972726  4.020593    C -0.020593
8   3.340075  3.102644  4.972810  3.926619    C  0.073381
9   2.648075  1.848566  4.972378  4.022322    C -0.022322
10  5.758662  5.521252  4.973703  4.133353    C -0.133353
11  7.012733  6.213270  4.974097  3.942728    C  0.057272
12  8.245313  5.546533  4.974276  4.170682    C -0.170682
13  1.051441  6.237731  4.972806  3.590398    C  0.409602
14  2.623578  7.809883  4.973289  3.503189    C  0.496811
15  2.301855  5.538761  4.972963  3.818856    C  0.181144
16  3.322549  6.559472  4.973289  3.960439    C  0.039561
17  3.314837  0.616006  4.972415  3.980080    C  0.019920
18  5.759803  4.122225  4.973507  3.941978    C  0.058022
19  4.739091  3.101513  4.973202  4.031799    C -0.031799
20  6.836150  7.635839  4.974361  4.078600    C -0.078600
21  1.225507  2.025155  4.972130  4.092335    C -0.092335
22  6.821242  2.040105  4.973617  6.148765    N -1.148765
23  1.240432  7.620906  4.973082  6.169547    N -1.169547
24  8.253057  0.608298  4.973962  8.275243   Ir  0.724757

## N1

In [6]:

f = open("bader/bare_N1_ACF.dat",'r')
lines = f.readlines()

bader = list()
for i,line in enumerate(lines[2:-4]):
    line = line.split()  # 줄 끝의 줄 바꿈 문자를 제거한다.
    bader.append(line)
f.close()

df_bare_N1 = pd.DataFrame(bader)
df_bare_N1.drop([0],axis=1)
df_bare_N1.columns = ["#","x","y","z","charge","min_dist","atomic vol"]
df_bare_N1 = df_bare_N1.drop(['#','min_dist','atomic vol'],axis=1)

atom_list = ['C'] *23 + ['N'] * 1 + ['Ir'] * 1
df_bare_N1['atom'] = atom_list


electron = [4,5,9]
net_list = list()
for i,atom in enumerate(atom_list) :
    if atom == "C" :
        net_list.append(-float(list(df_bare_N1['charge'])[i]) + electron[0])
    if atom == "N" :
        net_list.append(-float(list(df_bare_N1['charge'])[i]) + electron[1])
    if atom == "Ir" :
        net_list.append(-float(list(df_bare_N1['charge'])[i]) + electron[2])    
        
df_bare_N1['net'] = net_list
df_bare_N1 = df_bare_N1.astype({'x':'float', 'y':'float', 'z':'float', 'charge' : 'float'})

df_bare_N1

           x         y         z    charge atom       net
0   5.435926  1.837565  4.937766  4.015390    C -0.015390
1   4.736430  0.604624  4.937698  4.024136    C -0.024136
2   5.417934  7.837191  4.937638  3.987617    C  0.012383
3   4.739567  6.576078  4.937756  4.129624    C -0.129624
4   7.051927  3.453598  4.937755  4.107058    C -0.107058
5   8.284861  4.153113  4.937720  3.986489    C  0.013511
6   1.052314  3.471564  4.937589  4.039057    C -0.039057
7   2.313427  4.149916  4.937699  3.936276    C  0.063724
8   3.352231  3.107960  4.937720  3.807266    C  0.192734
9   2.642499  1.854326  4.937611  4.029073    C -0.029073
10  5.781528  5.537263  4.937757  4.020681    C -0.020681
11  7.035146  6.247006  4.937639  4.023257    C -0.023257
12  8.277688  5.585154  4.937724  4.005711    C -0.005711
13  1.068761  6.257026  4.937763  3.512447    C  0.487553
14  2.632460  7.820748  4.937793  3.570408    C  0.429592
15  2.319968  5.546464  4.937765  4.047919    C -0.047919
16  3.343022  6.569553  4.937792  3.887697    C  0.112303
17  3.304392  0.611803  4.937713  4.038852    C -0.038852
18  5.787564  4.141217  4.937773  3.934522    C  0.065478
19  4.748283  3.101935  4.937767  4.036210    C -0.036210
20  6.882121  2.007399  4.938144  4.156338    C -0.156338
21  1.212934  2.048689  4.937772  4.194885    C -0.194885
22  6.840807  7.676572  4.937808  4.190049    C -0.190049
23  1.267127  7.622389  4.937974  6.197015    N -1.197015
24  8.264855  0.624690  4.939779  8.122022   Ir  0.877978

## N0

In [7]:

f = open("bader/bare_N0_ACF.dat",'r')
lines = f.readlines()

bader = list()
for i,line in enumerate(lines[2:-4]):
    line = line.split()  # 줄 끝의 줄 바꿈 문자를 제거한다.
    bader.append(line)
f.close()

df_bare_N0 = pd.DataFrame(bader)
df_bare_N0.drop([0],axis=1)
df_bare_N0.columns = ["#","x","y","z","charge","min_dist","atomic vol"]
df_bare_N0 = df_bare_N0.drop(['#','min_dist','atomic vol'],axis=1)

atom_list = ['C'] *24 + ['Ir'] * 1
df_bare_N0['atom'] = atom_list


electron = [4,9]
net_list = list()
for i,atom in enumerate(atom_list) :
    if atom == "C" :
        net_list.append(-float(list(df_bare_N0['charge'])[i]) + electron[0])
    #if atom == "N" :
    #    net_list.append(-float(list(df_bare_N1['charge'])[i]) + electron[1])
    if atom == "Ir" :
        net_list.append(-float(list(df_bare_N0['charge'])[i]) + electron[1])    
        
df_bare_N0['net'] = net_list
df_bare_N0 = df_bare_N0.astype({'x':'float', 'y':'float', 'z':'float', 'charge' : 'float'})


df_bare_N0

           x         y         z    charge atom       net
0   5.451866  1.861746  4.909058  4.116342    C -0.116342
1   4.772305  0.615785  4.908986  4.008332    C -0.008332
2   5.451891  7.863654  4.909236  4.110520    C -0.110520
3   4.754212  6.599218  4.909266  4.022096    C -0.022096
4   7.058541  3.468446  4.909081  4.026039    C -0.026039
5   8.304494  4.148017  4.909038  3.882038    C  0.117962
6   1.056649  3.468377  4.909150  4.122925    C -0.122925
7   2.321085  4.166058  4.909189  3.812396    C  0.187604
8   3.361015  3.126115  4.909128  3.953640    C  0.046360
9   2.663345  1.861679  4.909077  4.025056    C -0.025056
10  5.794160  5.559284  4.909185  4.161781    C -0.161781
11  7.058587  6.256956  4.909163  4.108709    C -0.108709
12  8.304526  5.577374  4.909090  4.017087    C -0.017087
13  1.056687  6.256896  4.909231  4.119795    C -0.119795
14  2.663370  7.863596  4.909255  4.021113    C -0.021113
15  2.321125  5.559222  4.909260  4.043791    C -0.043791
16  3.361061  6.599176  4.909276  3.943750    C  0.056250
17  3.342944  0.615742  4.909017  3.995966    C  0.004034
18  5.794120  4.166129  4.909134  3.929869    C  0.070131
19  4.754175  3.126174  4.909119  4.032082    C -0.032082
20  6.879094  2.041220  4.909239  4.057820    C -0.057820
21  1.236125  2.041162  4.909238  4.068265    C -0.068265
22  6.879111  7.684180  4.909342  4.050309    C -0.050309
23  1.236142  7.684122  4.909341  4.066857    C -0.066857
24  8.304525  0.615788  4.910266  8.303420   Ir  0.696580

# Cl

## N4

In [8]:

f = open("bader/Cl_N4_ACF.dat",'r')
lines = f.readlines()

bader = list()
for i,line in enumerate(lines[2:-4]):
    line = line.split()  # 줄 끝의 줄 바꿈 문자를 제거한다.
    bader.append(line)
f.close()

df_Cl_N4 = pd.DataFrame(bader)
df_Cl_N4.drop([0],axis=1)
df_Cl_N4.columns = ["#","x","y","z","charge","min_dist","atomic vol"]
df_Cl_N4 = df_Cl_N4.drop(['#','min_dist','atomic vol'],axis=1)

atom_list = ['C'] *20 + ['N'] * 4 + ['Ir'] * 1 +  ['Cl'] * 1
df_Cl_N4['atom'] = atom_list


electron = [4,5,9,7]
net_list = list()
for i,atom in enumerate(atom_list) :
    if atom == "C" :
        net_list.append(-float(list(df_Cl_N4['charge'])[i]) + electron[0])
    if atom == "N" :
        net_list.append(-float(list(df_Cl_N4['charge'])[i]) + electron[1])
    if atom == "Ir" :
        net_list.append(-float(list(df_Cl_N4['charge'])[i]) + electron[2])    
    if atom == "Cl" :
        net_list.append(-float(list(df_Cl_N4['charge'])[i]) + electron[3])  
        
df_Cl_N4['net'] = net_list
df_Cl_N4= df_Cl_N4.astype({'x':'float', 'y':'float', 'z':'float', 'charge' : 'float'})


df_Cl_N4

           x         y         z    charge atom       net
0   5.396824  1.843861  5.036142  3.614434    C  0.385566
1   4.726850  0.607356  5.042612  3.966084    C  0.033916
2   5.396805  7.752384  5.036077  3.613518    C  0.386482
3   4.702952  6.506274  5.028861  3.997067    C  0.002933
4   6.958273  3.405312  5.036096  3.567529    C  0.432471
5   8.194774  4.075294  5.042488  3.958248    C  0.041752
6   1.049745  3.405287  5.036120  3.506927    C  0.493073
7   2.295851  4.099149  5.028869  3.803001    C  0.196999
8   3.305049  3.089959  5.028890  3.950476    C  0.049524
9   2.611196  1.843849  5.036141  3.499696    C  0.500304
10  5.712151  5.497084  5.028840  4.146565    C -0.146565
11  6.958264  6.190946  5.036055  3.513411    C  0.486589
12  8.194769  5.520973  5.042488  4.080234    C -0.080234
13  1.049736  6.190929  5.036101  3.586607    C  0.413393
14  2.611177  7.752381  5.036054  3.570244    C  0.429756
15  2.295846  5.497078  5.028848  4.033122    C -0.033122
16  3.305030  6.506277  5.028861  3.869504    C  0.130496
17  3.281178  0.607350  5.042633  3.969197    C  0.030803
18  5.712155  4.099163  5.028860  3.862246    C  0.137754
19  4.702963  3.089964  5.028890  4.007816    C -0.007816
20  6.764941  2.037178  5.030142  6.164577    N -1.164577
21  1.243070  2.037163  5.030161  6.210738    N -1.210738
22  6.764923  7.559078  5.030104  6.153259    N -1.153259
23  1.243052  7.559055  5.030101  6.187554    N -1.187554
24  8.194783  0.607378  5.155466  7.826553   Ir  1.173447
25  8.195186  0.607513  7.427072  7.341392   Cl -0.341392

## N3

In [9]:

f = open("bader/Cl_N3_ACF.dat",'r')
lines = f.readlines()

bader = list()
for i,line in enumerate(lines[2:-4]):
    line = line.split()  # 줄 끝의 줄 바꿈 문자를 제거한다.
    bader.append(line)
f.close()

df_Cl_N3 = pd.DataFrame(bader)
df_Cl_N3.drop([0],axis=1)
df_Cl_N3.columns = ["#","x","y","z","charge","min_dist","atomic vol"]
df_Cl_N3 = df_Cl_N3.drop(['#','min_dist','atomic vol'],axis=1)

atom_list = ['C'] *21 + ['N'] * 3 + ['Ir'] * 1 +  ['Cl'] * 1
df_Cl_N3['atom'] = atom_list


electron = [4,5,9,7]
net_list = list()
for i,atom in enumerate(atom_list) :
    if atom == "C" :
        net_list.append(-float(list(df_Cl_N3['charge'])[i]) + electron[0])
    if atom == "N" :
        net_list.append(-float(list(df_Cl_N3['charge'])[i]) + electron[1])
    if atom == "Ir" :
        net_list.append(-float(list(df_Cl_N3['charge'])[i]) + electron[2])    
    if atom == "Cl" :
        net_list.append(-float(list(df_Cl_N3['charge'])[i]) + electron[3])  
        
df_Cl_N3['net'] = net_list
df_Cl_N3 = df_Cl_N3.astype({'x':'float', 'y':'float', 'z':'float', 'charge' : 'float'})

df_Cl_N3

           x         y         z    charge atom       net
0   5.394206  1.820160  4.988174  4.028505    C -0.028505
1   4.712788  0.597156  5.009805  3.933404    C  0.066596
2   5.392346  7.768931  5.013816  3.632901    C  0.367099
3   4.711395  6.522874  4.991255  4.005228    C -0.005228
4   7.004660  3.430628  4.988123  4.022939    C -0.022939
5   8.227649  4.112046  5.009680  4.057922    C -0.057922
6   1.055885  3.432418  5.013715  3.612404    C  0.387596
7   2.301936  4.113387  4.991164  3.809995    C  0.190005
8   3.318869  3.091402  4.981667  3.950210    C  0.049790
9   2.603135  1.842163  5.001411  3.554048    C  0.445952
10  5.733395  5.505965  4.981716  4.147412    C -0.147412
11  6.982620  6.221717  5.001406  3.505125    C  0.494875
12  8.226404  5.552763  5.005457  3.986308    C  0.013692
13  1.059194  6.213518  4.988637  3.501588    C  0.498412
14  2.611265  7.765610  4.988670  3.561572    C  0.438428
15  2.304238  5.509349  4.977460  4.036196    C -0.036196
16  3.315435  6.520562  4.977496  3.876545    C  0.123455
17  3.272081  0.598391  5.005548  3.946775    C  0.053225
18  5.749188  4.115269  4.967985  3.905578    C  0.094422
19  4.709564  3.075628  4.967991  4.008512    C -0.008512
20  6.820627  2.004213  5.014768  4.126556    C -0.126556
21  1.237377  2.055250  5.015883  6.177953    N -1.177953
22  6.769506  7.587474  5.015914  6.123912    N -1.123912
23  1.251117  7.573677  4.989112  6.221347    N -1.221347
24  8.201036  0.623812  5.162308  7.951053   Ir  1.048947
25  8.205849  0.618994  7.447370  7.316011   Cl -0.316011

## N2

In [10]:

f = open("bader/Cl_N2_ACF.dat",'r')
lines = f.readlines()

bader = list()
for i,line in enumerate(lines[2:-4]):
    line = line.split()  # 줄 끝의 줄 바꿈 문자를 제거한다.
    bader.append(line)
f.close()

df_Cl_N2 = pd.DataFrame(bader)
df_Cl_N2.drop([0],axis=1)
df_Cl_N2.columns = ["#","x","y","z","charge","min_dist","atomic vol"]
df_Cl_N2 = df_Cl_N2.drop(['#','min_dist','atomic vol'],axis=1)

atom_list = ['C'] *22 + ['N'] * 2 + ['Ir'] * 1 +  ['Cl'] * 1
df_Cl_N2['atom'] = atom_list


electron = [4,5,9,7]
net_list = list()
for i,atom in enumerate(atom_list) :
    if atom == "C" :
        net_list.append(-float(list(df_Cl_N2['charge'])[i]) + electron[0])
    if atom == "N" :
        net_list.append(-float(list(df_Cl_N2['charge'])[i]) + electron[1])
    if atom == "Ir" :
        net_list.append(-float(list(df_Cl_N2['charge'])[i]) + electron[2])    
    if atom == "Cl" :
        net_list.append(-float(list(df_Cl_N2['charge'])[i]) + electron[3])  
        
df_Cl_N2['net'] = net_list
df_Cl_N2 = df_Cl_N2.astype({'x':'float', 'y':'float', 'z':'float', 'charge' : 'float'})


df_Cl_N2

           x         y         z    charge atom       net
0   5.431320  1.825141  4.948341  4.103369    C -0.103369
1   4.754301  0.598002  4.959950  3.977660    C  0.022340
2   5.424776  7.788462  4.958420  3.627390    C  0.372610
3   4.736798  6.542890  4.932714  4.139352    C -0.139352
4   7.030003  3.462793  4.960814  4.033631    C -0.033631
5   8.254869  4.161886  4.967455  3.938766    C  0.061234
6   1.036815  3.462775  4.960765  4.030758    C -0.030758
7   2.297910  4.129224  4.928133  3.915106    C  0.084894
8   3.336335  3.086826  4.920758  3.882986    C  0.117014
9   2.635507  1.825137  4.948233  3.932908    C  0.067092
10  5.753145  5.528646  4.926964  4.012825    C -0.012825
11  7.003112  6.248870  4.950909  3.511416    C  0.488584
12  8.254873  5.599471  4.959723  3.966761    C  0.033239
13  1.063714  6.248836  4.950880  3.544437    C  0.455563
14  2.642016  7.788450  4.958333  3.574193    C  0.425807
15  2.313685  5.528630  4.926939  4.047646    C -0.047646
16  3.330001  6.542884  4.932691  3.872687    C  0.127313
17  3.312534  0.597995  4.959906  3.986707    C  0.013293
18  5.768912  4.129239  4.928179  3.907816    C  0.092184
19  4.730493  3.086832  4.920781  4.019472    C -0.019472
20  6.867413  2.030626  5.005298  4.116269    C -0.116269
21  1.199422  2.030618  5.005145  4.131554    C -0.131554
22  6.793267  7.609304  4.977679  6.152446    N -1.152446
23  1.273543  7.609263  4.977567  6.203678    N -1.203678
24  8.254905  0.658355  5.203082  8.061350   Ir  0.938650
25  8.255550  0.651204  7.486583  7.308813   Cl -0.308813

## N2-t

In [11]:

f = open("bader/Cl_N2t_ACF.dat",'r')
lines = f.readlines()

bader = list()
for i,line in enumerate(lines[2:-4]):
    line = line.split()  # 줄 끝의 줄 바꿈 문자를 제거한다.
    bader.append(line)
f.close()

df_Cl_N2t = pd.DataFrame(bader)
df_Cl_N2t.drop([0],axis=1)
df_Cl_N2t.columns = ["#","x","y","z","charge","min_dist","atomic vol"]
df_Cl_N2t = df_Cl_N2t.drop(['#','min_dist','atomic vol'],axis=1)

atom_list = ['C'] *22 + ['N'] * 2 + ['Ir'] * 1 +  ['Cl'] * 1
df_Cl_N2t['atom'] = atom_list


electron = [4,5,9,7]
net_list = list()
for i,atom in enumerate(atom_list) :
    if atom == "C" :
        net_list.append(-float(list(df_Cl_N2t['charge'])[i]) + electron[0])
    if atom == "N" :
        net_list.append(-float(list(df_Cl_N2t['charge'])[i]) + electron[1])
    if atom == "Ir" :
        net_list.append(-float(list(df_Cl_N2t['charge'])[i]) + electron[2])    
    if atom == "Cl" :
        net_list.append(-float(list(df_Cl_N2t['charge'])[i]) + electron[3])  
        
df_Cl_N2t['net'] = net_list
df_Cl_N2t = df_Cl_N2t.astype({'x':'float', 'y':'float', 'z':'float', 'charge' : 'float'})


df_Cl_N2t

           x         y         z    charge atom       net
0   5.431452  1.857953  4.983615  3.616455    C  0.383545
1   4.752179  0.610871  4.957028  4.073250    C -0.073250
2   5.422443  7.824561  4.921133  4.023122    C -0.023122
3   4.729305  6.563080  4.907433  4.005112    C -0.005112
4   7.003337  3.429868  4.984182  3.524006    C  0.475994
5   8.250428  4.109167  4.958227  3.978940    C  0.021060
6   1.036772  3.438869  4.919365  4.005614    C -0.005614
7   2.298249  4.132004  4.906432  3.811011    C  0.188989
8   3.332331  3.097912  4.906536  4.020124    C -0.020124
9   2.639207  1.836435  4.919495  3.933838    C  0.066162
10  5.763395  5.528996  4.907517  3.925720    C  0.074280
11  7.024870  6.222136  4.921263  4.021603    C -0.021603
12  8.251403  5.547659  4.958470  4.091400    C -0.091400
13  1.058266  6.231121  4.983220  3.596418    C  0.403582
14  2.630168  7.803027  4.983786  3.510635    C  0.489365
15  2.308868  5.527840  4.947013  4.026540    C -0.026540
16  3.333451  6.552450  4.947403  3.940792    C  0.059208
17  3.313689  0.609894  4.956648  3.987250    C  0.012750
18  5.752769  4.133146  4.947619  4.134284    C -0.134284
19  4.728160  3.108537  4.947229  4.006909    C -0.006909
20  6.842974  7.642671  4.968907  4.071671    C -0.071671
21  1.218656  2.018321  4.966567  4.104187    C -0.104187
22  6.807735  2.053565  5.028287  6.104716    N -1.104716
23  1.253880  7.607403  5.027754  6.135799    N -1.135799
24  8.253007  0.608285  5.238152  7.991399   Ir  1.008601
25  8.253461  0.608349  7.528219  7.359205   Cl -0.359205

## N1

In [12]:

f = open("bader/Cl_N1_ACF.dat",'r')
lines = f.readlines()

bader = list()
for i,line in enumerate(lines[2:-4]):
    line = line.split()  # 줄 끝의 줄 바꿈 문자를 제거한다.
    bader.append(line)
f.close()

df_Cl_N1 = pd.DataFrame(bader)
df_Cl_N1.drop([0],axis=1)
df_Cl_N1.columns = ["#","x","y","z","charge","min_dist","atomic vol"]
df_Cl_N1 = df_Cl_N1.drop(['#','min_dist','atomic vol'],axis=1)

atom_list = ['C'] *23 + ['N'] * 1 + ['Ir'] * 1 +  ['Cl'] * 1
df_Cl_N1['atom'] = atom_list


electron = [4,5,9,7]
net_list = list()
for i,atom in enumerate(atom_list) :
    if atom == "C" :
        net_list.append(-float(list(df_Cl_N1['charge'])[i]) + electron[0])
    if atom == "N" :
        net_list.append(-float(list(df_Cl_N1['charge'])[i]) + electron[1])
    if atom == "Ir" :
        net_list.append(-float(list(df_Cl_N1['charge'])[i]) + electron[2])    
    if atom == "Cl" :
        net_list.append(-float(list(df_Cl_N1['charge'])[i]) + electron[3])  
        
df_Cl_N1['net'] = net_list
df_Cl_N1 = df_Cl_N1.astype({'x':'float', 'y':'float', 'z':'float', 'charge' : 'float'})
df_Cl_N1

           x         y         z    charge atom       net
0   5.426877  1.845184  4.942358  4.016821    C -0.016821
1   4.738578  0.610949  4.904519  3.953454    C  0.046546
2   5.434555  7.859032  4.865964  4.019332    C -0.019332
3   4.759132  6.587408  4.844467  3.944257    C  0.055743
4   7.044300  3.462639  4.942347  4.111392    C -0.111392
5   8.278527  4.150949  4.904521  3.974330    C  0.025670
6   1.030472  3.454916  4.865874  4.041253    C -0.041253
7   2.302097  4.130333  4.844430  3.959872    C  0.040128
8   3.332801  3.095216  4.843645  3.897917    C  0.102083
9   2.620098  1.822324  4.866599  3.990696    C  0.009304
10  5.794263  5.556709  4.843681  3.819003    C  0.180997
11  7.067147  6.269415  4.866690  3.995574    C  0.004426
12  8.294201  5.587305  4.907379  4.005722    C -0.005722
13  1.081367  6.249575  4.947857  3.520748    C  0.479252
14  2.639869  7.808134  4.947867  3.564970    C  0.435030
15  2.332170  5.534583  4.882950  4.001147    C -0.001147
16  3.354894  6.557342  4.882977  4.085652    C -0.085652
17  3.302216  0.595273  4.907327  3.965048    C  0.034952
18  5.780788  4.157015  4.883951  4.118238    C -0.118238
19  4.732493  3.108702  4.883944  3.991705    C  0.008295
20  6.861920  2.027593  5.059130  4.080653    C -0.080653
21  1.193629  2.024706  4.923251  4.193620    C -0.193620
22  6.864755  7.695886  4.923349  4.182225    C -0.182225
23  1.276830  7.612636  5.041875  6.129068    N -1.129068
24  8.247807  0.641715  5.350128  8.121758   Ir  0.878242
25  8.266805  0.622994  7.623887  7.315545   Cl -0.315545

## N0

In [13]:

f = open("bader/Cl_N0_ACF.dat",'r')
lines = f.readlines()

bader = list()
for i,line in enumerate(lines[2:-4]):
    line = line.split()  # 줄 끝의 줄 바꿈 문자를 제거한다.
    bader.append(line)
f.close()

df_Cl_N0 = pd.DataFrame(bader)
df_Cl_N0.drop([0],axis=1)
df_Cl_N0.columns = ["#","x","y","z","charge","min_dist","atomic vol"]
df_Cl_N0 = df_Cl_N0.drop(['#','min_dist','atomic vol'],axis=1)

atom_list = ['C'] *24 + ['Ir'] * 1 +  ['Cl'] * 1
df_Cl_N0['atom'] = atom_list


electron = [4,9,7]
net_list = list()
for i,atom in enumerate(atom_list) :
    if atom == "C" :
        net_list.append(-float(list(df_Cl_N0['charge'])[i]) + electron[0])
    #if atom == "N" :
    #    net_list.append(-float(list(df_Cl_N1['charge'])[i]) + electron[1])
    if atom == "Ir" :
        net_list.append(-float(list(df_Cl_N0['charge'])[i]) + electron[1])    
    if atom == "Cl" :
        net_list.append(-float(list(df_Cl_N0['charge'])[i]) + electron[2])  
        
df_Cl_N0['net'] = net_list

df_Cl_N0 = df_Cl_N0.astype({'x':'float', 'y':'float', 'z':'float', 'charge' : 'float'})

df_Cl_N0

           x         y         z    charge atom       net
0   5.463427  1.846880  4.860030  4.102106    C -0.102106
1   4.774311  0.615757  4.840730  3.988653    C  0.011347
2   5.463418  7.878449  4.860291  4.106159    C -0.106159
3   4.760151  6.607149  4.838502  4.004192    C -0.004192
4   7.073346  3.456816  4.860013  4.015276    C -0.015276
5   8.304478  4.145951  4.840783  3.890233    C  0.109767
6   1.041820  3.456815  4.860205  4.099385    C -0.099385
7   2.313127  4.160084  4.838445  3.802091    C  0.197909
8   3.355003  3.118179  4.838385  3.940065    C  0.059935
9   2.651744  1.846889  4.860091  4.004977    C -0.004977
10  5.802052  5.565253  4.838421  4.147210    C -0.147210
11  7.073334  6.268532  4.860177  4.012809    C -0.012809
12  8.304468  5.579418  4.840835  4.098816    C -0.098816
13  1.041798  6.268480  4.860246  4.096616    C -0.096616
14  2.651718  7.878432  4.860249  4.008723    C -0.008723
15  2.313117  5.565233  4.838476  4.033468    C -0.033468
16  3.354989  6.607149  4.838492  3.932132    C  0.067868
17  3.340848  0.615757  4.840741  4.007689    C -0.007689
18  5.802063  4.160087  4.838329  3.919999    C  0.080001
19  4.760165  3.118196  4.838334  4.016729    C -0.016729
20  6.892505  2.027743  4.970995  4.059336    C -0.059336
21  1.222686  2.027744  4.971159  4.079116    C -0.079116
22  6.892488  7.697594  4.971325  4.051351    C -0.051351
23  1.222652  7.697553  4.971263  4.072753    C -0.072753
24  8.304547  0.615773  5.427044  8.183020   Ir  0.816980
25  8.305439  0.615995  7.692318  7.327094   Cl -0.327094

In [14]:
df_summary = pd.DataFrame({"N" : ['4','4','3','3','2','2','2t','2t','1','1','0','0'] , 
                           'species' : ["Ir","Cl","Ir","Cl","Ir","Cl","Ir","Cl","Ir","Cl","Ir","Cl"],
                           'opt' : [df_bare_N4.loc[24,"net"],np.nan,df_bare_N3.loc[24,"net"],np.nan,df_bare_N2.loc[24,"net"],np.nan,df_bare_N2t.loc[24,"net"],np.nan,df_bare_N1.loc[24,"net"],np.nan,df_bare_N0.loc[24,"net"],np.nan],
                           'Cl_top' : [df_Cl_N4.loc[24,"net"],df_Cl_N4.loc[25,"net"],df_Cl_N3.loc[24,"net"],df_Cl_N3.loc[25,"net"],df_Cl_N2.loc[24,"net"],df_Cl_N2.loc[25,"net"],df_Cl_N2t.loc[24,"net"],df_Cl_N2t.loc[25,"net"],df_Cl_N1.loc[24,"net"],df_Cl_N1.loc[25,"net"],df_Cl_N0.loc[24,"net"],df_Cl_N0.loc[25,"net"]]
                          })

df_summary['diff'] = df_summary['Cl_top'] - df_summary['opt']
df_summary['ΔG_Cl'] = [1.08,np.nan,0.70,np.nan,0.49,np.nan,0.50,np.nan,0.35,np.nan,0.00,np.nan]
df_summary

     N species       opt    Cl_top      diff  ΔG_Cl
0    4      Ir  1.185311  1.173447 -0.011864   1.08
1    4      Cl       NaN -0.341392       NaN    NaN
2    3      Ir  0.818497  1.048947  0.230450   0.70
3    3      Cl       NaN -0.316011       NaN    NaN
4    2      Ir  0.671717  0.938650  0.266933   0.49
5    2      Cl       NaN -0.308813       NaN    NaN
6   2t      Ir  0.724757  1.008601  0.283844   0.50
7   2t      Cl       NaN -0.359205       NaN    NaN
8    1      Ir  0.877978  0.878242  0.000264   0.35
9    1      Cl       NaN -0.315545       NaN    NaN
10   0      Ir  0.696580  0.816980  0.120400   0.00
11   0      Cl       NaN -0.327094       NaN    NaN

In [15]:
base_dir = ""
file_nm = "bader.xlsx"
xlxs_dir = os.path.join(base_dir, file_nm)

with pd.ExcelWriter(xlxs_dir) as writer:
    df_summary.to_excel(writer, sheet_name = 'summary',na_rep = 'NaN',float_format = "%.2f")    
    df_bare_N4.to_excel(writer, sheet_name = 'bare_N4',na_rep = 'NaN',float_format = "%.2f")
    df_Cl_N4.to_excel(writer, sheet_name = 'Cl_N4',na_rep = 'NaN',float_format = "%.2f")
    df_bare_N3.to_excel(writer, sheet_name = 'bare_N3',na_rep = 'NaN',float_format = "%.2f")
    df_Cl_N3.to_excel(writer, sheet_name = 'Cl_N3',na_rep = 'NaN',float_format = "%.2f")
    df_bare_N2.to_excel(writer, sheet_name = 'bare_N2',na_rep = 'NaN',float_format = "%.2f")
    df_Cl_N2t.to_excel(writer, sheet_name = 'Cl_N2t',na_rep = 'NaN',float_format = "%.2f")
    df_bare_N2t.to_excel(writer, sheet_name = 'bare_N2t',na_rep = 'NaN',float_format = "%.2f")
    df_Cl_N2t.to_excel(writer, sheet_name = 'Cl_N2t',na_rep = 'NaN',float_format = "%.2f")
    df_bare_N1.to_excel(writer, sheet_name = 'bare_N2',na_rep = 'NaN',float_format = "%.2f")
    df_Cl_N1.to_excel(writer, sheet_name = 'Cl_N1',na_rep = 'NaN',float_format = "%.2f")    
    df_bare_N0.to_excel(writer, sheet_name = 'bare_N0',na_rep = 'NaN',float_format = "%.2f")
    df_Cl_N0.to_excel(writer, sheet_name = 'Cl_N0',na_rep = 'NaN',float_format = "%.2f")